name: Single Flow CI

on: 
  - workflow_dispatch:   

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run a Simple Test
        run: |
          echo "Running a test..."
          python -c "print('Hello, GitHub Actions!')"
