name: Sum Of Two Variable 
on:
  workflow_dispatch:

jobs:
  sum:
    runs-on: ubuntu-latest
    steps:
      - name: Sum of number
        run: |
          sum=$Number1+$Number2
        env:
          Number1: ${{  vars.NUMBER1  }}
          Number2: ${{  vars.NUMBER2  }}
          
      - name: Display the sum
        run: echo "The sum is $sum"
          
          
           
